### ISSUE TITLE
[ERRO] 2023-05-24 13:31:17 flag provided but not defined: -html [cli.go:41]

### ISSUE THREAD

**Issue by Only-MrLi** [chaitin/xpoc#2]
./xpoc_darwin_arm64 -t https://example.com -html result.html

 [ERRO] 2023-05-24 13:31:17 flag provided but not defined: -html [cli.go:41]

**Comment by chinaykc** [comment]
提示部分有误，造成了误导，抱歉。实际上是使用-o result.json或者-o result.html进行结果的输出。
在0.0.2版本已经修复该问题，可以通过xpoc upgrade命令进行升级。感谢支持。
