### ISSUE TITLE
v0.1.0 会导致本地配置文件被清空

### ISSUE THREAD

**Issue by charis3306** [chaitin/xpoc#37]
[INF] 24-07-31 11:40:53 使用以下位置的配置文件：C:\Users\lbb\.xray\xpoc\xpoc-config.yaml [app.go:447]
[INF] 24-07-31 11:40:53 未能正确加载配置文件或配置文件不存在，使用默认配置 [app.go:449]
[INF] 24-07-31 11:40:53 :upgrade: no update found. you are currently using the latest version. [upgrade.go:40]

**Comment by Jarcis-cy** [comment]
是的，因为本次对配置文件有较大更新，所以在changelog中也有所提醒

**Comment by charis3306** [comment]
> 是的，因为本次对配置文件有较大更新，所以在changelog中也有所提醒

怎么解决这个问题啊。使用 --config 也创建不了啊

**Comment by Jarcis-cy** [comment]
https://docs.xray.cool/tools/BasicFunc#configuration-file

看看这个

**Comment by charis3306** [comment]
好的解决了。非常感谢！！！
