### ISSUE TITLE
启动时，提示 gopath 报错

### ISSUE THREAD

**Issue by 1nformation** [chaitin/xpoc#39]
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/30901f6d-dca8-449e-bd8e-8aa69585b105">

**Comment by 1nformation** [comment]
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/9b4a72c7-1641-41e4-85f9-6f972044610a">

**Comment by Jarcis-cy** [comment]
这个是我们插件的问题，近期会更新一下插件就好了
